"""
Django settings for ExamineLab project.

Generated by 'django-admin startproject' using Django 2.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""
import os
from djangocodemirror.settings import *
from djangocodemirror.helper import codemirror_settings_update


CODEMIRROR_SETTINGS['my_mode'] = {
    'mode': {  
        'name': 'python',
        'version': 3,
        'singleLineStringErrors': False,
    },
    'tabSize': 2,
    'theme': 'eclipse',
    #'spellcheck': True,
    #'autocorrect': True,
    'extraKeys': {  
        'Ctrl-Q': 'toggleComment',
        #'Ctrl-Space': 'autocomplete',
    },
    'lineNumbers': True,
    'lineWrapping': True,
    'autofocus': True,
    'scrollbarStyle': 'overlay',
    'modes': [  
        'python'
    ],
    'keyMap': 'sublime',
    'autoCloseBrackets': '()[]{}\'\'""',
    
    #'styleActiveLine': True,

    'matchBrackets': True,
    'highlightSelectionMatches': True,
    'addons': [  
        'CodeMirror/addon/edit/matchbrackets.js',
        'CodeMirror/addon/comment/comment.js',
        'CodeMirror/addon/scroll/simplescrollbars.js',
        'CodeMirror/addon/edit/closebrackets.js',
        'CodeMirror/keymap/sublime.js',
        
        
        #'CodeMirror/addon/selection/active-line.js',
        #'CodeMirror/addon/hint/show-hint.js',
        #'CodeMirror/addon/hint/anyword-hint.js',
        #'CodeMirror/addon/hint/python-hint.js',
    ]
}
# TODO Добавить больше функционала 
# anywordhint, activeline, complete, match-highlighter, placeholder, search
# fullscreen, lint



# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'n413(ma0!tl3d$x%8aeb!3)=o*+fcz3%78b!!c=dtdf3jj3ka2'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'main.apps.MainConfig',
    'djangocodemirror'
]

AUTH_USER_MODEL = "main.User"

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ExamineLab.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ExamineLab.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'

MEDIA_ROOT =  os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'
