# Generated by Django 2.2 on 2019-05-06 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='launch_command_win',
        ),
        migrations.RemoveField(
            model_name='language',
            name='optional_win',
        ),
        migrations.AddField(
            model_name='language',
            name='input_help',
            field=models.CharField(default='', max_length=550),
        ),
        migrations.AddField(
            model_name='language',
            name='output_help',
            field=models.CharField(default='', max_length=550),
        ),
        migrations.AlterField(
            model_name='language',
            name='launch_command_linux',
            field=models.CharField(max_length=550),
        ),
        migrations.AlterField(
            model_name='language',
            name='optional_linux',
            field=models.CharField(default='rm <path>*', max_length=351),
        ),
    ]
