# Generated by Django 2.2 on 2019-05-12 19:43

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='completed_courses',
            field=models.ManyToManyField(blank=True, related_name='completed_courses', to='main.Course'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='completed_tasks',
            field=models.ManyToManyField(blank=True, related_name='completed_tasks', to='main.Task'),
        ),
    ]
