# Generated by Django 2.1.1 on 2019-03-10 09:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutorial',
            old_name='tutorial_content',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='tutorial',
            old_name='tutorial_title',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='tutorial',
            name='tutorial_published',
        ),
        migrations.AddField(
            model_name='tutorial',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 10, 12, 29, 7, 692018), verbose_name='date published'),
        ),
    ]
