# Generated by Django 2.2 on 2019-05-06 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190506_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='input_help',
            field=models.TextField(default='', max_length=550),
        ),
        migrations.AlterField(
            model_name='language',
            name='output_help',
            field=models.TextField(default='', max_length=550),
        ),
    ]
