# Generated by Django 2.2 on 2019-05-15 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_statistics'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='statistics',
            unique_together={('user', 'date')},
        ),
    ]
