# Generated by Django 2.2 on 2019-05-12 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190512_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permissiongroup',
            name='permissions',
        ),
        migrations.RemoveField(
            model_name='usercoursespecificpermissions',
            name='course',
        ),
        migrations.RemoveField(
            model_name='usercoursespecificpermissions',
            name='permission',
        ),
        migrations.RemoveField(
            model_name='usercoursespecificpermissions',
            name='user',
        ),
        migrations.DeleteModel(
            name='Permission',
        ),
        migrations.DeleteModel(
            name='PermissionGroup',
        ),
        migrations.DeleteModel(
            name='UserCourseSpecificPermissions',
        ),
    ]
