# Generated by Django 2.1.1 on 2019-03-13 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20190313_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='tasks',
            field=models.ManyToManyField(to='main.Task'),
        ),
        migrations.AddField(
            model_name='course',
            name='tasks',
            field=models.ManyToManyField(to='main.Task'),
        ),
        migrations.AddField(
            model_name='task',
            name='tests',
            field=models.ManyToManyField(to='main.Test'),
        ),
        migrations.AlterField(
            model_name='course',
            name='summary',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='summary',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
    ]
