# Generated by Django 2.1.1 on 2019-03-15 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20190313_1039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='tasks',
        ),
        migrations.RemoveField(
            model_name='course',
            name='tasks',
        ),
        migrations.RemoveField(
            model_name='task',
            name='tests',
        ),
        migrations.AddField(
            model_name='task',
            name='course_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.Course'),
        ),
        migrations.AddField(
            model_name='test',
            name='task_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.Task'),
        ),
    ]
