# Generated by Django 2.1.1 on 2019-03-15 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20190315_1207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='course_id',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='task_id',
            new_name='task',
        ),
    ]
