# Generated by Django 2.1.1 on 2019-04-04 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20190315_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='solution',
            field=models.TextField(blank=True, null=True),
        ),
    ]
