# Generated by Django 2.1.1 on 2019-04-26 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20190426_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='launch_command',
            field=models.CharField(default='./', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='language',
            name='optional_arguments',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
