# Generated by Django 2.1.1 on 2019-04-26 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20190426_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='optional_arguments',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
