# Generated by Django 2.1.1 on 2019-04-27 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20190427_1043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logs',
            name='content',
        ),
        migrations.AddField(
            model_name='logs',
            name='stderr',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='logs',
            name='stdout',
            field=models.TextField(blank=True),
        ),
    ]
