# Generated by Django 2.2 on 2019-04-27 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20190427_1152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='language',
            old_name='launch_command',
            new_name='launch_command_linux',
        ),
        migrations.RenameField(
            model_name='language',
            old_name='optional',
            new_name='optional_linux',
        ),
        migrations.AddField(
            model_name='language',
            name='launch_command_win',
            field=models.CharField(default='start <path>*', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='language',
            name='optional_win',
            field=models.CharField(default='del /f <path>*', max_length=351),
        ),
    ]
